link /nologo $(DEPENDS) $(LIBS) /OUT:$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
cl /nologo -c $(CFLAGS)  $(INPUT) /Fo$(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)
copy $(DEPENDS) $(TARGET)

